# Generated by Django 4.2.7 on 2025-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='posicao',
            field=models.IntegerField(blank=True, help_text='Posição no ranking de criminalidade', null=True),
        ),
    ]
