# Generated by Django 4.2.7 on 2025-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0002_cidade_posicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário Admin',
                'verbose_name_plural': 'Usuários Admin',
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mercadolivre', 'Mercado Livre'), ('amazon', 'Amazon'), ('magazineluiza', 'Magazine Luiza'), ('americanas', 'Americanas'), ('outros', 'Outros')], default='mercadolivre', max_length=20)),
                ('titulo', models.CharField(help_text='Título do cupom', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição do cupom')),
                ('codigo', models.CharField(help_text='Código do cupom', max_length=50)),
                ('link_acesso', models.URLField(help_text='Link para usar o cupom')),
                ('ativo', models.BooleanField(default=True, help_text='Se o cupom está ativo')),
                ('ordem_exibicao', models.IntegerField(default=1, help_text='Ordem de exibição (menor número aparece primeiro)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['ordem_exibicao', 'data_criacao'],
            },
        ),
    ]
