# Generated by Django 4.2.7 on 2025-09-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0003_adminuser_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='tipo',
            field=models.CharField(help_text='Nome da loja onde o cupom é válido', max_length=100),
        ),
    ]
