# Generated by Django 4.2.7 on 2025-09-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0004_alter_cupom_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='consulta_risco.adminuser'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('editor', 'Editor')], default='admin', max_length=20),
        ),
    ]
