# Generated by Django 4.2.7 on 2025-09-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0005_adminuser_criado_por_adminuser_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_criados', to='consulta_risco.adminuser'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_modificados', to='consulta_risco.adminuser'),
        ),
    ]
