# Generated by Django 4.2.7 on 2025-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0006_cupom_criado_por_cupom_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='cor_fundo_loja',
            field=models.CharField(default='#ff6b35', help_text='Cor de fundo do nome da loja (formato hexadecimal)', max_length=7),
        ),
    ]
