# Generated by Django 4.2.7 on 2025-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0007_cupom_cor_fundo_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de cupom', max_length=50, unique=True)),
                ('cor_fundo', models.CharField(help_text='Cor de fundo em formato hexadecimal', max_length=7)),
                ('cor_texto', models.CharField(default='#ffffff', help_text='Cor do texto em formato hexadecimal', max_length=7)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do tipo de cupom')),
                ('ativo', models.BooleanField(default=True, help_text='Se o tipo está ativo')),
                ('ordem_exibicao', models.IntegerField(default=1, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Cupom',
                'verbose_name_plural': 'Tipos de Cupom',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='cupom',
            name='tipo_cupom',
            field=models.ForeignKey(blank=True, help_text='Tipo de cupom com cor predefinida', null=True, on_delete=models.deletion.CASCADE, to='consulta_risco.tipocupom'),
        ),
        migrations.RenameField(
            model_name='cupom',
            old_name='tipo',
            new_name='loja',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='cor_fundo_loja',
        ),
    ]
