# Generated by Django 4.2.7 on 2025-10-02 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0008_auto_20251002_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocupom',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocupom',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
