# Generated by Django 4.2.7 on 2025-10-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0009_auto_20251002_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocupom',
            options={'ordering': ['ordem_exibicao', 'nome'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocupom',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se a loja está ativa'),
        ),
        migrations.AlterField(
            model_name='tipocupom',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da loja'),
        ),
        migrations.AlterField(
            model_name='tipocupom',
            name='nome',
            field=models.CharField(help_text='Nome da loja', max_length=50, unique=True),
        ),
    ]
