# Generated by Django 4.2.7 on 2025-10-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0010_alter_tipocupom_options_adminuser_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email do usuário que fez a avaliação', max_length=254)),
                ('cidade', models.CharField(help_text='Nome da cidade avaliada', max_length=100)),
                ('nota', models.IntegerField(help_text='Nota de 1 a 10 para o nível de segurança')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da avaliação')),
                ('estado', models.ForeignKey(help_text='Estado da cidade avaliada', on_delete=django.db.models.deletion.CASCADE, to='consulta_risco.estado')),
            ],
            options={
                'verbose_name': 'Avaliação de Segurança',
                'verbose_name_plural': 'Avaliações de Segurança',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('email', 'estado', 'cidade')},
            },
        ),
    ]
