# Generated by Django 4.2.7 on 2025-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0011_avaliacaoseguranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização dos dados')),
                ('descricao', models.CharField(default='Atualização automática do sistema', help_text='Descrição da atualização', max_length=200)),
            ],
            options={
                'verbose_name': 'Atualização do Sistema',
                'verbose_name_plural': 'Atualizações do Sistema',
            },
        ),
    ]
