# Generated by Django 4.2.7 on 2025-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0012_sistemaatualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='data_inicio',
            field=models.DateTimeField(blank=True, help_text='Data de início da validade do cupom', null=True),
        ),
        migrations.AddField(
            model_name='cupom',
            name='data_validade',
            field=models.DateTimeField(blank=True, help_text='Data de validade do cupom (deixar em branco para cupom sem prazo)', null=True),
        ),
    ]
