# Generated by Django 4.2.7 on 2025-10-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0013_cupom_data_inicio_cupom_data_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código do cupom (opcional)', max_length=50, null=True),
        ),
    ]
