# Generated by Django 4.2.7 on 2025-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0014_alter_cupom_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagina', models.CharField(help_text='Nome da página (ex: lgpd, faq, sobre)', max_length=100, unique=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização da página')),
                ('descricao', models.CharField(default='Atualização da página', help_text='Descrição da atualização', max_length=200)),
            ],
            options={
                'verbose_name': 'Atualização de Página',
                'verbose_name_plural': 'Atualizações de Páginas',
                'ordering': ['nome_pagina'],
            },
        ),
    ]
