# Generated by Django 4.2.7 on 2025-10-14 20:36

import consulta_risco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0015_paginaatualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoseguranca',
            name='data_avaliacao',
            field=models.DateTimeField(default=consulta_risco.models.get_brasilia_time, help_text='Data e hora da avaliação em UTC-3 (Brasília)'),
        ),
    ]
