# Generated by Django 4.2.7 on 2025-10-14 20:38

import consulta_risco.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0016_alter_data_avaliacao_utc3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoseguranca',
            name='data_avaliacao',
            field=consulta_risco.models.BrasiliaDateTimeField(default=consulta_risco.models.get_brasilia_time, help_text='Data e hora da avaliação em UTC-3 (Brasília)'),
        ),
    ]
