# Generated by Django 4.2.7 on 2025-11-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0017_use_brasilia_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude da cidade', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude da cidade', max_digits=10, null=True),
        ),
    ]
