# Generated by Django 4.2.7 on 2025-12-01 21:29

from django.db import migrations, models


def preencher_emails_vazios(apps, schema_editor):
    """Preenche emails vazios com um email temporário baseado no username"""
    AdminUser = apps.get_model('consulta_risco', 'AdminUser')
    for user in AdminUser.objects.filter(email__isnull=True) | AdminUser.objects.filter(email=''):
        # Criar email temporário baseado no username
        user.email = f"{user.username}@safetyscorebrasil.com.br"
        user.save()


def reverter_emails_temporarios(apps, schema_editor):
    """Reverte emails temporários para vazio"""
    AdminUser = apps.get_model('consulta_risco', 'AdminUser')
    for user in AdminUser.objects.filter(email__endswith='@safetyscorebrasil.com.br'):
        # Verificar se é um email temporário (mesmo username)
        if user.email.startswith(f"{user.username}@"):
            user.email = ''
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0019_add_indexes_avaliacao'),
    ]

    operations = [
        # Primeiro, preencher emails vazios
        migrations.RunPython(preencher_emails_vazios, reverter_emails_temporarios),
        # Depois, tornar o campo obrigatório
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
