# Generated by Django 4.2.7 on 2025-12-11 04:03

import consulta_risco.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0020_make_email_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliqueCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('data_clique', consulta_risco.models.BrasiliaDateTimeField(default=consulta_risco.models.get_brasilia_time, help_text='Data e hora do clique em UTC-3 (Brasília)')),
                ('cupom', models.ForeignKey(help_text='Cupom que foi clicado', on_delete=django.db.models.deletion.CASCADE, related_name='cliques', to='consulta_risco.cupom')),
            ],
            options={
                'verbose_name': 'Clique em Cupom',
                'verbose_name_plural': 'Cliques em Cupons',
                'ordering': ['-data_clique'],
                'indexes': [models.Index(fields=['cupom', 'data_clique'], name='clique_cupom_data_idx'), models.Index(fields=['data_clique'], name='clique_data_idx')],
            },
        ),
    ]
