# Generated by Django 4.2.7 on 2025-12-12 20:15

import consulta_risco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_risco', '0021_cliquecupom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='URL da página acessada', max_length=500)),
                ('nome_pagina', models.CharField(blank=True, help_text='Nome amigável da página', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário', null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade do usuário', max_length=100)),
                ('estado', models.CharField(blank=True, help_text='Estado (UF) do usuário', max_length=2)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('referer', models.URLField(blank=True, help_text='Página de origem (referer)')),
                ('data_acesso', consulta_risco.models.BrasiliaDateTimeField(default=consulta_risco.models.get_brasilia_time, help_text='Data e hora do acesso em UTC-3 (Brasília)')),
            ],
            options={
                'verbose_name': 'Acesso à Página',
                'verbose_name_plural': 'Acessos às Páginas',
                'ordering': ['-data_acesso'],
                'indexes': [models.Index(fields=['url', 'data_acesso'], name='acesso_url_data_idx'), models.Index(fields=['data_acesso'], name='acesso_data_idx'), models.Index(fields=['estado', 'cidade'], name='acesso_estado_cidade_idx')],
            },
        ),
    ]
